# Generated by Django 6.1.1 on 2026-09-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_education_full_name_alter_education_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='git_hub_url',
            new_name='github_url',
        ),
    ]
