# Generated by Django 6.1.1 on 2026-09-30 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_rename_git_hub_url_education_github_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Education',
            new_name='About',
        ),
    ]
